#!/bin/bash

clear
echo "🚀 CONFIGURAÇÃO ULTRA-RÁPIDA CODEIUM"
echo "=================================="
echo ""
echo "📋 TOKEN: zX3snOCGDE8FxO5aIwMBdgKjsWcE8zEfyY6tB6lIZ9U"
echo ""
echo "⚡ AGORA FAÇA ISSO:"
echo "1. Ctrl+Shift+P"
echo "2. Digite: Codeium: Provide Auth Token"
echo "3. Cole o token acima"
echo "4. Enter"
echo ""
echo "🔄 SE NÃO FUNCIONAR:"
echo "1. Ctrl+Shift+P" 
echo "2. Digite: Codeium: Sign In"
echo "3. Login no browser"
echo ""
echo "✅ TESTE:"
echo "Digite código no arquivo test-codeium.js"
echo "Deve aparecer sugestões automáticas"
echo ""
echo "📞 Se ainda não funcionar, o token pode estar expirado"
echo "   Gere novo em: https://codeium.com/profile?tab=tokens"
echo ""
echo "⏰ ECONOMIZE TEMPO: Use o método 'Sign In' se o token não funcionar!"
