// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
// Prefer VITE_SUPABASE_ANON_KEY; fallback to VITE_SUPABASE_PUBLISHABLE_KEY
const SUPABASE_ANON_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY ??
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Check if Supabase credentials are available
const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_ANON_KEY);

// Create a mock client for when Supabase is not configured
// This prevents runtime crashes in preview/development environments
const createMockClient = (): SupabaseClient<Database> => {
  const mockResponse = {
    data: null,
    error: {
      message: "Supabase not configured",
      details: "",
      hint: "",
      code: "NOT_CONFIGURED",
    },
  };

  const mockBuilder = {
    select: () => mockBuilder,
    insert: () => mockBuilder,
    update: () => mockBuilder,
    delete: () => mockBuilder,
    eq: () => mockBuilder,
    neq: () => mockBuilder,
    single: () => Promise.resolve(mockResponse),
    maybeSingle: () => Promise.resolve(mockResponse),
    limit: () => mockBuilder,
    order: () => mockBuilder,
    range: () => mockBuilder,
    then: (resolve: (value: typeof mockResponse) => void) =>
      Promise.resolve(mockResponse).then(resolve),
  };

  if (!isSupabaseConfigured) {
    console.warn(
      "⚠️ Supabase not configured. Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY environment variables."
    );
  }

  return {
    from: () => mockBuilder,
    auth: {
      getSession: () =>
        Promise.resolve({ data: { session: null }, error: null }),
      getUser: () => Promise.resolve({ data: { user: null }, error: null }),
      signInWithPassword: () =>
        Promise.resolve({
          data: { user: null, session: null },
          error: mockResponse.error,
        }),
      signUp: () =>
        Promise.resolve({
          data: { user: null, session: null },
          error: mockResponse.error,
        }),
      signOut: () => Promise.resolve({ error: null }),
      onAuthStateChange: () => ({
        data: { subscription: { unsubscribe: () => {} } },
      }),
    },
    storage: {
      from: () => ({
        upload: () =>
          Promise.resolve({ data: null, error: mockResponse.error }),
        download: () =>
          Promise.resolve({ data: null, error: mockResponse.error }),
        getPublicUrl: () => ({ data: { publicUrl: "" } }),
      }),
    },
    rpc: () => Promise.resolve(mockResponse),
    channel: () => ({
      on: () => ({ subscribe: () => {} }),
      subscribe: () => {},
      unsubscribe: () => {},
    }),
  } as unknown as SupabaseClient<Database>;
};

// Export the real client if configured, otherwise export a mock
export const supabase: SupabaseClient<Database> = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL!, SUPABASE_ANON_KEY!, {
      auth: {
        storage: typeof window !== "undefined" ? localStorage : undefined,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : createMockClient();

// Export a flag to check if Supabase is properly configured
export const isSupabaseAvailable = isSupabaseConfigured;
